#!/usr/bin/env zsh

#------- Editing of .profile file and refresh command -----------
alias :ra='source ~/.zsh/aliases'
alias :ea='vim ~/.zsh/aliases'

alias :rh='source ~/.zsh/helpers'
alias :eh='vim ~/.zsh/helpers'

alias :rz='source ~/.zsh/zshrc'
alias :ez='vim ~/.zsh/zshrc'

alias :ev='vim ~/.vim/vimrc'
alias :eh='vim /opt/boxen/repo/hiera/users/lawrencejones.yaml'
#----------------------------------------------------------------

#------- Kubernetes Aliases -------------------------------------
alias k13="/usr/local/Cellar/kubernetes-cli/1.13.3/bin/kubectl"
alias k='kubectl'
alias kd='kubectl describe'
alias ke='kubectl exec'
alias kei='kubectl exec -it'
alias kg='kubectl get'
alias kl='kubectl logs'
alias ks='kubectl get services'
alias kn='kubectl get nodes'
alias kp='kubectl get pods'
alias kcc='bash -c "kubectl config set-context \$0 --namespace=\$1 && kubectl config use-context \$0"'
alias kenv="kubectl get secret -o go-template='{{ range \$k, \$v := .data }}{{ \$k }}={{ \$v | base64decode }}'$'\n''{{ end }}'"

# Helper aliases
alias _k_currentNamespace='kubectl config view -o json | jq -r ".contexts | map(select(.name == \"$(kubectl config current-context)\")) | .[0].context.namespace"'
#----------------------------------------------------------------

#------- Draupnir Aliases ---------------------------------------
alias draupnir-context="bash -c 'cp -v ~/.draupnir.\$0 ~/.draupnir'"
#----------------------------------------------------------------

#------- Vim Commands -------------------------------------------
alias :q='exit'
alias :Q='exit'
alias vim='nvim'
#----------------------------------------------------------------

#------- Ruby ---------------------------------------------------
alias be='bundle exec'
alias bi='bundle install'
alias ctags-ruby-bundle='ctags -R --languages=ruby --exclude=.git --exclude=log $(bundle list --paths) .'
alias ispec='RAILS_ENV=integration be rspec'
alias pry-lib='bundle exec pry --exec "\$LOAD_PATH << File.expand_path(File.join(File.dirname(__FILE__), \"lib\")); true"'
alias sprung='pgrep spring ruby rails rake | xargs kill -9'
#----------------------------------------------------------------

#------- Golang -------------------------------------------------
# If not yet setup, docker volume create dep-pkg
alias dep-enter='docker run --rm --mount source=dep-pkg,target=/go/pkg -v "$HOME/Projects/golang/src:/go/src" -it golang:1.10 bash'
alias go-mod='GO111MODULE=on go mod'
#----------------------------------------------------------------

#------- Diffo-actions ------------------------------------------
alias diffocop="(cd \$(git rev-parse --show-toplevel) && git diff master --name-only --diff-filter=ACMRTUXB | grep '\.rb$' | tr '\n' ' ' | xargs bundle exec rubocop)"
#----------------------------------------------------------------

#------- Git Aliases --------------------------------------------
alias g='git'
alias git-init='git init && echo ".DS_Store" > .gitignore'
alias gs='git status'
alias gsp='git status -- .'
alias ga='git add -A'
alias gca='git commit -v --amend'
alias gco='git checkout'
alias gcb='git checkout -b'
alias gac='git add -A :/ && git commit -a -v'
alias gd='git diff'
alias gdh='git diff HEAD'
alias gb='git branch'
alias gp='git push'
alias gpcb='git push origin $(git rev-parse --abbrev-ref HEAD)'
alias gpfh='git push -f origin $(git rev-parse --abbrev-ref HEAD)'
alias gr='git rebase'
alias gri='git rebase -i'
alias grc='git rebase --continue'
alias gm='git merge'
alias gpl='git pull'
#----------------------------------------------------------------

#------- Templating ---------------------------------------------
template-init() {
  if [[ "$#" -eq 1 ]]; then
    echo "Requires destination directory!"
    exit 255
  fi

  git clone https://github.com/$1 $2 && \
    cd $2 && \
    cat README.md && \
    rm -rf .git README.md && \
    git init && git add -A && git commit -am "Init from template $1"
}
alias latex-init='template-init lawrencejones/latex-template'
alias d3-init='template-init lawrencejones/d3-template'
alias js-init='template-init lawrencejones/js-template'
#----------------------------------------------------------------

#------- OS X Apps ----------------------------------------------
alias skim='open -a /Applications/Skim.app'
#----------------------------------------------------------------

#------- Utilities ----------------------------------------------
alias ll='ls -lh'
alias listpath='echo $PATH | tr ":" "\n"'
alias tmux='tmux -2' # colors!!!
alias twoup='lpr -o number-up=2 -o page-border=single'
alias mocha='mocha --compilers coffee:coffee-script/register'
alias ar='chdir $(git rev-parse --show-toplevel)'
alias ssh='compile-ssh-conf && ssh'
alias curl-json='function() { curl $1 | pp.js }'
alias pub-cp='cat ~/.ssh/id_rsa.pub | pbcopy'
alias rest-console='chdir $(mktemp -d /tmp/rest-console.XXXX) && $(echo "#!/bin/zsh\ncurl --args" > request.rest) && chmod a+x request.rest && tmux split-window -h "vim request.rest"'
alias plain-paste='pbpaste | pbcopy'
alias tmuxcp='tmux show-buffer | pbcopy'
alias curl-time='curl -w "@$HOME/dotfiles/nix/curl/curl-timing-output.txt"'
alias by='bpython'
alias lab-ssh='ssh -o StrictHostKeyChecking=no'
alias pg_format='pg_format --comma-start --spaces 2'
#----------------------------------------------------------------

#------  Work folder access -------------------------------------
alias projects='chdir /Users/lawrencejones/Projects'
alias sesquis='chdir /Users/lawrencejones/Projects/sesquis'
alias journal='chdir /Users/lawrencejones/Projects/journal'
#----------------------------------------------------------------

#------- PostgreSQL ---------------------------------------------
alias pg-start='pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start'
alias pg-stop='pg_ctl -D /usr/local/var/postgres stop -s -m fast'
#----------------------------------------------------------------

#------- Imperial Aliases ---------------------------------------
alias cate-token="git log | head -1 | awk -F' ' '{ print \$NF }' > ~/cate_token.txt"
#----------------------------------------------------------------
