#!/bin/bash
# GoCardless custom env

# Load dev config
export GC_GIT=$HOME/Projects
[ -f $GC_GIT/scripts/dev_env/env_setup.sh ] && . $GC_GIT/scripts/dev_env/env_setup.sh

# Load pry session with gocardless pro client
alias pro-client="source ~/env/gc.keys && pry --exec \"require_relative '$HOME/Projects/scripts/pro-client-repl/pro-client.rb'\""

alias gc='gocardless-dir'
gocardless-dir() {
  if [[ "$#" -eq 0 ]]; then

    echo """
    Desc:  Pulls and changes to gc repo
    Usage: gc <repo-name>
    Examples...

        gc payments-service

    """

  else
    if [ ! -d "$HOME/Projects/$1" ]; then
      git clone https://github.com/gocardless/$1 $HOME/Projects/$1 || \
        return
    fi
    cd $HOME/Projects/$1
    [ -z "$TMUX" ] && tmux -2
  fi
}

gc-ssh() {
  if [[ "$#" -eq 0 ]]; then

    echo """
    Desc:  Connects to GC servers
    Usage: gc-ssh <host>
    Examples...

        gc worker-service-live01.production

    """

  else
    ssh -p $GC_PORT $1
  fi
}
