#!/usr/bin/env zsh

alias p='project'
project() {
  if [[ "$#" -eq 0 ]]; then

    echo """
    Desc:  Pulls and changes to gh repos
    Usage: p <repo-name>
    Examples...

        p dotfiles  # automatically selects LawrenceJones/dotfiles
        p icdocsoc/website  # standard gh url

    """

  else
    ghUrl=$([[ "$1" =~ '/' ]] && echo $1 || echo "LawrenceJones/$1")
    projectDir=$(basename $ghUrl)

    if [ ! -d "$HOME/Projects/$projectDir" ]; then
      git clone git@github.com:$ghUrl $HOME/Projects/$projectDir || \
        return
    fi

    cd $HOME/Projects/$projectDir
    [ -z "$TMUX" ] && tmux -2
  fi
}

alias c='cookbook'
cookbook() {
  book=$1; : ${book:=""}
  cd "$HOME/Projects/chef-mono/cookbooks/$book"
}

edit-all() {
  if [[ "$#" -eq 0 ]]; then
    echo """
    Desc:  Given a wildcard, will load queue for vim editing
    Usage: edit-all <file-pattern>
    Examples...

        edit-all '*.coffee'

    """
  else
    find . -name "$1" -exec vim {} \;
  fi
}

sr() {
  if [[ "$#" -eq 0 ]]; then
    echo """
    Desc:  Search and replace with sed
    Usage: sr <source-regex> <replacement>
    Examples...

        sr 'var (\w+);' 'let \$1;'

    """
  else
    ag "$1" -l | xargs perl -p -i -e "s/$1/$2/g"
  fi
}

trim() {
  sed 's/^\s*//' | sed 's/\s*$//'
}

diffospec() {
  if [ "$1" == "--help" ]; then

    echo """
    Desc:  Runs rspec against files that have changed from a different commit
    Usage: diffospec <sha?>
    Examples...

        diffospec  # compares against HEAD^ by default
        diffospec 3efc2  # compares against #3efc2

    """

  else

    originalPath=$(pwd)
    cd $(git rev-parse --show-toplevel)

    ref=$1; if [ -z "$ref" ]; then ref='HEAD^'; fi
    echo "Spec'ing against $ref"

    specsWhereFileHasChangedPattern=$(
    git diff "$ref" --name-only --diff-filter=ACMRTUXB \
    | ack -v spec \
    | perl -wnl -e '/^[^\/]+\/(.+)\.rb$/ and print "-wholename \"**/$1_spec.rb\" -o"' \
    | tr '\n' ' ' \
    | sed 's/ -o\s*$//'
    )

    if [ -n "${specswherefilehaschangedpattern// }" ];
    then
      specsWhereFileHasChanged=$(find spec $(echo $specsWhereFileHasChangedPattern | xargs))
    else
      specsWhereFileHasChanged=""
    fi

    specsThatHaveChanged=$(git diff "$ref" --name-only --diff-filter=ACMRTUXB | ack spec.rb)
    specsToRun=$(echo $specsThatHaveChanged'\n'$specsWhereFileHasChanged | sort -u | ack "\S")

    if [ "$specsToRun" =~ '^ *$' ];
    then
      echo "No specs to run!"
    else
      echo $specsToRun | sed 's/^/- /'
      rspec $(echo $specsToRun | xargs)
    fi

    cd $originalPath

  fi
}

git-current-branch() {
  git rev-parse --abbrev-ref HEAD
}

git-parent-branch() {
  git show-branch -a 2&>/dev/null \
  | ack '\*' \
  | ack -v "$(git-current-branch)" \
  | head -n1 \
  | perl -wnl -e '/\[([^\^\]]*)/ and print $1;'
}

token() {
  if [[ "$#" -eq 0 ]]; then

    echo """
    Desc:  Extracts token from given line
    Usage: token <index> <delimiter?>
    Examples...

        token 2  # whitespace default
        token 1 \"\\\t\"  # tab delimited

    """

  else

    index=$1; : ${index:="1"}
    delimiter=$2; : ${delimiter:=$'\t'}

    cut -d"$delimiter" -f"$index"

  fi
}

line() {
  if [[ "$#" -eq 0 ]]; then

    echo """
    Desc:  Select lines from output
    Usage: line <index-from> <how-many-lines>
    Examples...

        echo -e \"1\\\n2\\\n3\\\n4\\\n5\" | line 2 3  # > 2\\\n3\\\n4

    """

  else

    index=$1; : ${index:="1"}
    count=$2; : ${count:="1"}

    head -n `expr $index + $count - 1` | tail -$count

  fi
}

github() {
  git_remote=$(git remote -v | head -1 | perl -wnl -e '/github.com.([^ ]*)/ and print $1')
  echo Opening $git_remote...
  open "https://github.com/$git_remote"
}

ckdir() {
  mkdir -p $1 && cd $_
}

last-screenshot() {
  echo "$HOME/Dropbox/Screenshots/$(ls --color=no -t $HOME/Dropbox/Screenshots | head -n 1)"
}

aws-keychain-activate() {
  if [[ "$#" -eq 0 ]]; then
    echo """
    Usage: aws-keychain-activate <repo-name>
    Desc:  Exports aws credentials from keychain into current env
    Examples...

        aws-keychain-activate gc-iam

    Available envs:

        $(aws-keychain ls | xargs | sed 's/ /\n        /g')

    """
  else
    aws-keychain exec "$1" bash <<-BASH | source /dev/stdin
    echo -e """
    export AWS_ACCESS_KEY_ID=\"\$AWS_ACCESS_KEY_ID\"
    export AWS_SECRET_ACCESS_KEY=\"\$AWS_SECRET_ACCESS_KEY\"
    """
BASH
  fi
}
